import { StyleSheet,Dimensions } from "react-native";

export default StyleSheet.create({
    genericContainer:{
        flex:1
    },
    container2:{
        flex:2
    },
    container3:{
        flex:3
    },
    container4:{
        flex:4
    },
    container5:{
        flex:5
    },
    container6:{
        flex:6
    },
    positionRelative:{
        position:"relative"
    },
    positionAbsolute:{
        position:"absolute"
    },
    column:{
        display:'flex',
        flexDirection:'column'
    },
    row:{
        display:'flex',
        flexDirection:'row'
    },
    spaceAround:{
        justifyContent:"space-around"
    },
    rowHeader:{
        display:'flex',
        flexDirection:'row',
        justifyContent:'space-between'
    },
    fullScreenSize: {
        width: Dimensions.get('window').width,
        height: Dimensions.get('window').height
    },
    centerItems:{
        display:'flex',
        justifyContent:"center",
        alignItems:"center"
    },
    centerVertical:{
        alignItems:'center'
    },
    centerHorizontal:{
        justifyContent:'center'
    },
    paddingContainer:{
        paddingVertical:30,
        paddingHorizontal:6
    },
    paddingContainer2:{
        paddingHorizontal:10,
        paddingVertical:10
    },
    paddingBottom:{
        paddingBottom:15
    },
    paddingX:{
        paddingHorizontal:10
    },
    paddingY:{
        paddingVertical:20
    },
    marginY:{
        marginVertical:10
    },
    brandColorBg: {
        backgroundColor:'#613DC1',
    },
    branColorText:{
        color:'#613DC1'
    },
    secondaryBg:{
        backgroundColor: '#858AE3'
    },
    secondaryColorText:{
        color:'#858AE3'
    },
    trdBg:{
        backgroundColor:'#97DFFC'
    },
    trdText:{
        color:'#97DFFC'
    },
    lightColorbg:{
        backgroundColor:'#FBFAFF'
    },
    lightColorText:{
        color:'#FBFAFF'
    },
    darkColorBG:{
        backgroundColor:'#4E148C'
    },
    darkColorText:{
        color:'#4E148C'
    },
    titleFont:{
        fontSize:40,
    },
    whiteColor:{
        color:'#f6f6f6'
    },
    boldFont:{
        fontWeight:'bold'
    },
    smallText:{
        fontSize:13
    },
    halfWidth:{
        width:'50%'
    },
    normalTextSize:{
        fontSize:20
    },
    textCenter:{
        textAlign:"center"
    },
    lineThrough:{
        textDecorationLine:'line-through'
    },
    underline:{
        textDecorationLine:"underline"
    },
    textMaiusc:{
        textTransform:"uppercase"
    },
    marginRigth:{
        marginRight:10
    },
    paddingHeader:{
        paddingHorizontal:3,
        paddingVertical:5
    },
    buttonBoxHeader:{
        display:'flex',
        justifyContent:'center',
        alignItems:'center'
    },
    inputBox: {
        height: 40,
        width:300,
        margin: 12,
        borderWidth: 2,
        padding: 10,
        borderColor:'#EF233C'
    },
    buttonSos:{
        height:200,
        width:200,
        display:'flex',
        justifyContent:'center',
        alignItems:"center",
        borderRadius:200
    },
    sosText:{
        fontSize:70
    },
    circleButton:{
        height:40,
        width:40,
        borderRadius:40,
        display:'flex',
        alignItems:'center',
        justifyContent:'center'
    },
    squareButton:{
        paddingHorizontal:20,
        paddingVertical:10,
        borderRadius:10,
        display:'flex',
        alignItems:'center',
        justifyContent:'center'
    },
    image:{
        width:'100%',
        height:40
    },
    imageBg:{
        width:'100%',
        height:70
    },
    wpButton:{
        backgroundColor:'#25D366'
    }
})